server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    bufferDurationMs: 400
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: true
      local: false
    plugins:
      - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.0"
        snapshot: false
    youtubeConfig:
      clients:
        - TVHTML5_SIMPLY
        - WEB
      cipherServer: "https://cipher.kikkia.dev/"
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.0"
      repository: "https://maven.lavalink.dev/releases"
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
  environment: ""
logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG
